mybatis:
  type-aliases-package: com.neo.qiaoqiaochat.dao

server:
  port: 8081
  tomcat:
    uri-encoding: utf-8


spring:
  mvc:
    servlet:
      path: /web
  application:
    name: web
  cloud:
    nacos:
      discovery:
        server-addr: 124.70.210.202:8848
        namespace: e571b4ce-0995-4ede-853c-254ef0c57267
