netty:
  port: 8888
  websocketPort: 8800


mybatis:
  type-aliases-package: com.neo.qiaoqiaochat.dao

server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

audience:
  # 代表这个JWT的接收对象,存入audience
  clientId: 098f6bcd4621d373cade4e832627b4f6
  # 密钥, 经过Base64加密, 可自行替换
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  # JWT的签发主体，存入issuer
  name: restapiuser
  # 过期时间，时间戳
  expiresSecond: 172800


spring:
  redis:
    database: 0
    host: 124.70.210.202
    port: 6378
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  datasource:
    druid:
      url: jdbc:mysql://124.70.210.202:3308/qiaoqiao?useUnicode=true&characterEncoding=utf8
      username: root
      #      password: XWO3fk/WzrOLp5VGXppQ6EieW0BSX/6CYr8GHduAc2eDCzn2bPWesH5KwlA6e71Dy3Ijk4uuK89Z5tLOpwt1VA==
      #      connect-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALxzg7MfNQPGQNY6HigCSdhRiOS9NXX9bd3Fpjx19Ial8RSqWyeK36F1dMxrtMoGxjEVw3AT1lGete6fYva1n/8CAwEAAQ==

      password: 0rhyme-coveting6-1Hogs-win4
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat,slf4j,wall
      #连接池建立时创建的初始化连接数
      initial-size: 5
      #连接池中最大的活跃连接数
      max-active: 20
      #连接池中最小的活跃连接数
      min-idle: 5
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30000
      #是否在获得连接后检测其可用性
      test-on-borrow: false
      #是否在连接放回连接池后检测其可用性
      test-on-return: false
      #是否在连接空闲一段时间后检测其可用性
      test-while-idle: true