netty:
  port: 8888
  websocketPort: 8800


mybatis:
  mapper-locations: classpath*:mappers/*.xml

server:
  port: 8080
  tomcat:
    uri-encoding: utf-8



spring:
  mvc:
    servlet:
      path: /ws
  application:
    name: websocket
  cloud:
    nacos:
      discovery:
        server-addr: 124.70.210.202:8848
        namespace: e571b4ce-0995-4ede-853c-254ef0c57267
