# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v12
      with:
        repositories: '[{ "id": "central", "name": "central", "url": "http://central", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } },{ "id": "nexus_self", "name": "Nexus", "url": "http://124.70.210.202:9001/repository/maven-public/", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } }]'
        plugin_repositories: '[{ "id": "central", "name": "central", "url": "http://central", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" }}, { "id": "nexus_self", "name": "Nexus", "url": "http://124.70.210.202:9001/repository/maven-public/", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" }}]'
        servers: '[{ "id": "nexus_self", "username": "admin", "password": "freefall-6Fief-4goatskin-klutz6-Ale1" }]'
        mirrors: '[{ "id": "nexus_self", "mirrorOf": "nexus_self", "url": "http://124.70.210.202:9001/repository/maven-public" }]'
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true
    - name: build docker image
      run: docker build -t qiaoqiaochat:v1 .
    - name: tag image
      run: docker tag  qiaoqiaochat:v1 swr.cn-east-3.myhuaweicloud.com/neo/qiaoqiaochat:v1
    - name: login
      run: ${{ secrets.LOGIN_COMMAND }}
    - name: push image
      run: docker push swr.cn-east-3.myhuaweicloud.com/neo/qiaoqiaochat:v1
    - uses: webfactory/ssh-agent@v0.1.1
      with:
        ssh-private-key: ${{ secrets.ID_RSA }}
    - name: Setup knownhosts
      run: ssh-keyscan 124.70.210.202 >> ~/.ssh/known_hosts
    - name: Run SSH Command
      run: ssh github@124.70.210.202 "sh run.sh"
