# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: build docker image
      run: docker build -t neo/qiaoqiaochat:v1 .
    - name: tag image
      run: docker tag  neo/qiaoqiaochat:v1 124.70.210.202:5000/neo/qiaoqiaochat:v1
    - name: push image
      run: dockerd --insecure-registry 124.70.210.202:5000
        docker push 124.70.210.202:5000/neo/qiaoqiaochat:v1
